package com.daimengshi.ddcms.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsRole<M extends BaseDmsRole<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "DmsRole:add";
    public static final String ACTION_DELETE = "DmsRole:delete";
    public static final String ACTION_UPDATE = "DmsRole:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public void setFlagKey(java.lang.String flagKey) {
		set("flag_key", flagKey);
	}
	
	public java.lang.String getFlagKey() {
		return getStr("flag_key");
	}

	public void setIsOpen(java.lang.String isOpen) {
		set("is_open", isOpen);
	}
	
	public java.lang.String getIsOpen() {
		return getStr("is_open");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}

	public void setLastUpdataAcct(java.lang.String lastUpdataAcct) {
		set("last_updata_acct", lastUpdataAcct);
	}
	
	public java.lang.String getLastUpdataAcct() {
		return getStr("last_updata_acct");
	}

	public void setLastUpdataTime(java.util.Date lastUpdataTime) {
		set("last_updata_time", lastUpdataTime);
	}
	
	public java.util.Date getLastUpdataTime() {
		return get("last_updata_time");
	}

}
