package com.daimengshi.ddcms.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsConfig<M extends BaseDmsConfig<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "DmsConfig:add";
    public static final String ACTION_DELETE = "DmsConfig:delete";
    public static final String ACTION_UPDATE = "DmsConfig:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}
	
	public java.lang.String getKey() {
		return getStr("key");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public void setLastUpdataAcct(java.lang.String lastUpdataAcct) {
		set("last_updata_acct", lastUpdataAcct);
	}
	
	public java.lang.String getLastUpdataAcct() {
		return getStr("last_updata_acct");
	}

	public void setLastUpdataTime(java.util.Date lastUpdataTime) {
		set("last_updata_time", lastUpdataTime);
	}
	
	public java.util.Date getLastUpdataTime() {
		return get("last_updata_time");
	}

}
