package com.daimengshi.ddcms.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsLog<M extends BaseDmsLog<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "DmsLog:add";
    public static final String ACTION_DELETE = "DmsLog:delete";
    public static final String ACTION_UPDATE = "DmsLog:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setLastUpdataAcct(java.lang.String lastUpdataAcct) {
		set("last_updata_acct", lastUpdataAcct);
	}
	
	public java.lang.String getLastUpdataAcct() {
		return getStr("last_updata_acct");
	}

	public void setLastUpdataTime(java.util.Date lastUpdataTime) {
		set("last_updata_time", lastUpdataTime);
	}
	
	public java.util.Date getLastUpdataTime() {
		return get("last_updata_time");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	public java.lang.String getBrowser() {
		return getStr("browser");
	}

	public void setOperation(java.lang.String operation) {
		set("operation", operation);
	}
	
	public java.lang.String getOperation() {
		return getStr("operation");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
