package com.daimengshi.ddcms.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsLinks<M extends BaseDmsLinks<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "DmsLinks:add";
    public static final String ACTION_DELETE = "DmsLinks:delete";
    public static final String ACTION_UPDATE = "DmsLinks:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIsOpen(java.lang.String isOpen) {
		set("is_open", isOpen);
	}
	
	public java.lang.String getIsOpen() {
		return getStr("is_open");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public void setLastUpdataAcct(java.lang.String lastUpdataAcct) {
		set("last_updata_acct", lastUpdataAcct);
	}
	
	public java.lang.String getLastUpdataAcct() {
		return getStr("last_updata_acct");
	}

	public void setLastUpdataTime(java.util.Date lastUpdataTime) {
		set("last_updata_time", lastUpdataTime);
	}
	
	public java.util.Date getLastUpdataTime() {
		return get("last_updata_time");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setLogoUrl(java.lang.String logoUrl) {
		set("logo_url", logoUrl);
	}
	
	public java.lang.String getLogoUrl() {
		return getStr("logo_url");
	}

}
