package com.daimengshi.ddcms.service.entity.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class DmsBaseRes<M extends DmsBaseRes<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Res:add";
    public static final String ACTION_DELETE = "Res:delete";
    public static final String ACTION_UPDATE = "Res:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setPid(Long pid) {
		set("pid", pid);
	}

	public Long getPid() {
		return getLong("pid");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setDes(String des) {
		set("des", des);
	}

	public String getDes() {
		return getStr("des");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return getStr("url");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}

	public Integer getLevel() {
		return getInt("level");
	}

	public void setIconCls(String iconCls) {
		set("iconCls", iconCls);
	}

	public String getIconCls() {
		return getStr("iconCls");
	}

	public void setSeq(Long seq) {
		set("seq", seq);
	}

	public Long getSeq() {
		return getLong("seq");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return getStr("type");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return getStr("status");
	}

	public void setLastUpdAcct(String lastUpdAcct) {
		set("lastUpdAcct", lastUpdAcct);
	}

	public String getLastUpdAcct() {
		return getStr("lastUpdAcct");
	}

	public void setLastUpdTime(java.util.Date lastUpdTime) {
		set("lastUpdTime", lastUpdTime);
	}

	public java.util.Date getLastUpdTime() {
		return get("lastUpdTime");
	}

	public void setNote(String note) {
		set("note", note);
	}

	public String getNote() {
		return getStr("note");
	}

}
