package com.daimengshi.ddcms.admin.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsPermission<M extends BaseDmsPermission<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "DmsPermission:add";
    public static final String ACTION_DELETE = "DmsPermission:delete";
    public static final String ACTION_UPDATE = "DmsPermission:update";


    @Override
    protected String addAction() {
        return ACTION_ADD;
    }

    @Override
    protected String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    protected String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setMid(java.lang.String mid) {
		set("mid", mid);
	}
	
	public java.lang.String getMid() {
		return getStr("mid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
