package com.daimengshi.ddcms.admin.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsArticle<M extends BaseDmsArticle<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "DmsArticle:add";
    public static final String ACTION_DELETE = "DmsArticle:delete";
    public static final String ACTION_UPDATE = "DmsArticle:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setArticleTitle(java.lang.String articleTitle) {
		set("article_title", articleTitle);
	}
	
	public java.lang.String getArticleTitle() {
		return getStr("article_title");
	}

	public void setArticleContent(java.lang.String articleContent) {
		set("article_content", articleContent);
	}
	
	public java.lang.String getArticleContent() {
		return getStr("article_content");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

}
