package com.daimengshi.ddcms.service.entity.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.service.entity.model.base.BaseDmsArticleComment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_article_comment", primaryKey = "id")
public class DmsArticleComment extends BaseDmsArticleComment<DmsArticleComment> {
	
}
