package com.daimengshi.ddcms.service.entity.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.service.entity.model.base.BaseDmsArticleType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_article_type", primaryKey = "id")
public class DmsArticleType extends BaseDmsArticleType<DmsArticleType> {
	
}
