package com.daimengshi.ddcms.service.entity.model;


import com.daimengshi.ddcms.service.entity.model.base.BaseDmsConfig;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_config", primaryKey = "id")
public class DmsConfig extends BaseDmsConfig<DmsConfig> {
	
}
