package com.daimengshi.ddcms.service.entity.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.service.entity.model.base.BaseDmsLinks;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_links", primaryKey = "id")
public class DmsLinks extends BaseDmsLinks<DmsLinks> {
	
}
