package com.daimengshi.ddcms.service.entity.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.service.entity.model.base.BaseDmsLog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_log", primaryKey = "id")
public class DmsLog extends BaseDmsLog<DmsLog> {
	
}
