package com.daimengshi.ddcms.service.entity.model;


import com.daimengshi.ddcms.service.entity.model.base.BaseDmsRole;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_role", primaryKey = "id")
public class DmsRole extends BaseDmsRole<DmsRole> {
    public static final DmsRole dao = new DmsRole();

}
