package com.daimengshi.ddcms.service.entity.model;


import com.daimengshi.ddcms.service.entity.model.base.BaseDmsUser;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_user", primaryKey = "id")
public class DmsUser extends BaseDmsUser<DmsUser> {
    public static final DmsUser dao = new DmsUser();

    /**
     * 获取用户角色
     *
     * @return
     */
    public DmsRole getUserRole() {
        DmsUserRole userRole = DmsUserRole.dao.findFirst("select * from dms_user_role WHERE dms_user_role.uid = ?", getStr("id"));
        if (userRole == null) {
            return null;
        }
        DmsRole dmsRole = userRole.getRole();
        return dmsRole;
    }




}
