package com.daimengshi.ddcms.admin.model;

import com.daimengshi.ddcms.admin.model.base.BaseDmsArticle;
import com.jfinal.plugin.activerecord.Db;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_article", primaryKey = "id")
public class DmsArticle extends BaseDmsArticle<DmsArticle> {


    public DmsUser getUser() {
        DmsUser user = DmsUser.dao.findFirst(Db.getSql("article.getUser"),getStr("uid"));
        return user;
    }
}
