package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsArticle;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_article", primaryKey = "id")
public class DmsArticle extends BaseDmsArticle<DmsArticle> {
	
}
