package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsConfig;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_config", primaryKey = "id")
public class DmsConfig extends BaseDmsConfig<DmsConfig> {
	
}
