package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsMenuType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_menu_type", primaryKey = "id")
public class DmsMenuType extends BaseDmsMenuType<DmsMenuType> {
    public static final DmsMenuType dao = new DmsMenuType();
}
