package com.daimengshi.ddcms.admin.model;

import com.daimengshi.ddcms.admin.model.base.BaseDmsMenu;
import com.jfinal.plugin.activerecord.Db;
import io.jboot.db.annotation.Table;

import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_menu", primaryKey = "id")
public class DmsMenu extends BaseDmsMenu<DmsMenu> {
    public static final DmsMenu dao = new DmsMenu();

    /**
     * 获取菜单类型
     *
     * @return
     */
    public DmsMenuType getMenuType() {
        return DmsMenuType.dao.findFirst(Db.getSql("menu.getMenuType"), getStr("type_id"));
    }

    /**
     * 获取子菜单
     *
     * @return
     */
    public List<DmsMenu> getSubDmsMenu() {
        return DmsMenu.dao.find(Db.getSql("menu.getSubDmsMenu"), getStr("id"));
    }

    /**
     * 获取父类
     *
     * @return
     */
    public DmsMenu getSuperDmsMenu() {
        return DmsMenu.dao.findByIdWithoutCache(getStr("super_id"));
    }


}
