package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsMenu;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_menu", primaryKey = "id")
public class DmsMenu extends BaseDmsMenu<DmsMenu> {
    private String superName;
    private String typeName;

    public String getSuperName() {
        return superName;
    }

    public void setSuperName(String superName) {
        this.superName = superName;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}
