package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsMenu;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_menu", primaryKey = "id")
public class DmsMenu extends BaseDmsMenu<DmsMenu> {
}
