package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsPermission;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_permission", primaryKey = "id")
public class DmsPermission extends BaseDmsPermission<DmsPermission> {
    public static final DmsPermission dao = new DmsPermission();

}
