package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsRolePermission;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_role_permission", primaryKey = "id")
public class DmsRolePermission extends BaseDmsRolePermission<DmsRolePermission> {
	
}
