package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsRolePermission;

import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_role_permission", primaryKey = "id")
public class DmsRolePermission extends BaseDmsRolePermission<DmsRolePermission> {
    public static final DmsRolePermission dao = new DmsRolePermission();


    /**
     * 更具角色权限ID 查询当前角色的所有权限
     *
     * @return
     */
    public List<DmsPermission> getUserRolePermissions() {
        List<DmsPermission> rolePermissions = DmsPermission.dao.find("SELECT * from dms_permission WHERE dms_permission.id = ?", getStr("pid"));
        return rolePermissions;
    }

}
