package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_role", primaryKey = "id")
public class DmsRole extends BaseDmsRole<DmsRole> {
	
}
