package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsRole;

import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_role", primaryKey = "id")
public class DmsRole extends BaseDmsRole<DmsRole> {
    public static final DmsRole dao = new DmsRole();


    /**
     * 根据id获取当前角色的权限组
     *
     * @return
     */
    public List<DmsRolePermission> getRolePermissions() {
        List<DmsRolePermission> rolePermissions = DmsRolePermission.dao.find("SELECT * from dms_role_permission WHERE dms_role_permission.rid = ?", getStr("id"));

        return rolePermissions;
    }
}
