package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsSession;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_session", primaryKey = "id")
public class DmsSession extends BaseDmsSession<DmsSession> {
	
}
