package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsUserRole;

import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_user_role", primaryKey = "id")
public class DmsUserRole extends BaseDmsUserRole<DmsUserRole> {
    public static final DmsUserRole dao = new DmsUserRole();


    /**
     * 通过rid获取关联的所有角色
     * @return
     */
    public List<DmsRole> getRoles(){
        return DmsRole.dao.find("select * from dms_role WHERE dms_role.id = ?",getStr("rid"));
    }
}
