package com.daimengshi.ddcms.admin.model;

import com.daimengshi.ddcms.admin.model.base.BaseDmsUser;
import io.jboot.db.annotation.Table;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_user", primaryKey = "id")
public class DmsUser extends BaseDmsUser<DmsUser> {
    public static final DmsUser dao = new DmsUser();

    /**
     * 获取用户角色
     *
     * @return
     */
    public DmsRole getUserRole() {
        DmsUserRole userRole = DmsUserRole.dao.findFirst("select * from dms_user_role WHERE dms_user_role.uid = ?", getStr("id"));
        if (userRole == null) {
            return null;
        }
        DmsRole dmsRole = userRole.getRole();
        return dmsRole;
    }


    /**
     * 获取用有权限
     *
     * @return
     */
    public List<DmsPermission> getAllUserPermissions() {
        List<DmsPermission> permissions = new ArrayList<>();
        DmsRole userRole = getUserRole();
        if (userRole == null) {
            return null;
        }

        for (DmsRolePermission rolePermission : userRole.getRolePermissions()) {//得到角色中的角色权限
            permissions.addAll(rolePermission.getUserRolePermissions());
        }
        return permissions;
    }


}
