package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsUserRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_user_role", primaryKey = "id")
public class DmsUserRole extends BaseDmsUserRole<DmsUserRole> {
	
}
