package com.daimengshi.ddcms.admin.model;

import com.daimengshi.ddcms.admin.model.base.BaseDmsUser;
import io.jboot.db.annotation.Table;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_user", primaryKey = "id")
public class DmsUser extends BaseDmsUser<DmsUser> {
    public static final DmsUser dao = new DmsUser();

    /**
     * 获取用户角色
     *
     * @return
     */
    public List<DmsRole> getUserRoles() {
        List<DmsRole> dmsRoleList = new ArrayList<>();
        List<DmsUserRole> userRoles = DmsUserRole.dao.find("select * from dms_user_role WHERE dms_user_role.uid = ?", getStr("id"));

        for (DmsUserRole userRole : userRoles) {
            dmsRoleList.addAll(userRole.getRoles());
        }
        return dmsRoleList;
    }


    /**
     * 获取用户所有权限
     *
     * @return
     */
    public List<DmsPermission> getAllUserPermissions() {
        List<DmsPermission> permissions = new ArrayList<>();
        for (DmsRole role : getUserRoles()) {                                   //得到所有角色
            for (DmsRolePermission rolePermission : role.getRolePermissions()) {//得到所有角色中的角色权限
                permissions.addAll(rolePermission.getUserRolePermissions());    //获取所有角色权限对象
            }
        }
        return permissions;
    }


}
