package com.daimengshi.ddcms.admin.model;

import io.jboot.db.annotation.Table;
import com.daimengshi.ddcms.admin.model.base.BaseDmsUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "dms_user", primaryKey = "id")
public class DmsUser extends BaseDmsUser<DmsUser> {
	
}
